project:
  type: website
  output-dir: _site
  resources:
    - img/**

website:
  title: "NACE recodification with RAG"

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    theme: cosmo
    grid:
      body-width: 1100px
    reference-location: margin
    code-copy: true
    code-overflow: wrap
    lightbox: true

execute:
  eval: true
  cache: true
  warning: false
